[package]
name = "unlocker-abi"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.unlocker]
path = ".."

[dependencies.elrond-wasm]
version = "0.21.1"

[dependencies.elrond-wasm-debug]
version = "0.21.1"
